@token = 

POST https://localhost:7241/api/Job/Create
content-type: application/json
Authorization: Bearer {{token}}

{
  "title": "CPA",
  "employerName": "Tight Britches :-]",
  "description": "Number wrangler.",
  "startDate": "2021-01-21"
}